name: Test Examples
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Check Python Example
        if: always()
        working-directory: tree-sitter/python
        run: |
          pip install -r requirements.txt
          python main.py
      - name: Check Rust Example
        if: always()
        working-directory: tree-sitter/rust
        run: cargo run
      - name: Check TypeScript Example 
        if: always()
        working-directory: tree-sitter/typescript
        run: |
          npm install
          node_modules/.bin/ts-node app.ts
